// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string InsertGuidPackageString = "15429751-4477-4d4b-9317-a1c8f76e9d92";
        public const string InsertGuidCommandSetString = "16be331d-1f33-42a1-864f-56ecccd07734";
        public static Guid InsertGuidPackage = new Guid(InsertGuidPackageString);
        public static Guid InsertGuidCommandSet = new Guid(InsertGuidCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int InsertGroup = 0x0100;
        public const int InsertDropDown = 0x0101;
        public const int InsertCommands = 0x0102;
        public const int InsertGuidCommand = 0x0105;
    }
}
